In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("cuda working", torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")
    print("cpu working")

cpu working


In [3]:
#1 load the dataset
#2 basic prprocessing with the data
#3 Training process
#4 creat the model
#5 forward propagation
#6 loss calculation
#7 backward propagation
#8 paramter update
#9 Model evaluation

In [19]:
#so the very first creat the class for nn

class NeuralNetwrok(nn.Module):
  def __init__(self,features):    #constructor for the class to initalize the value
    super().__init__()                  #call the neural netork functions
    self.linear = nn.Linear(features,1)
    self.sigmoid = nn.Sigmoid()

    #forward propagation
  def forward(self,x):
    x = self.linear(x)
    x = self.sigmoid(x)

    return x


In [20]:
#1 creat a dataset
features = torch.rand(10,5)

#creat the  model
model = NeuralNetwrok(features.shape[1])

In [21]:
features.shape

torch.Size([10, 5])

In [23]:
model(features).shape #to get the y pred for every rows

torch.Size([10, 1])

In [25]:
model.linear.weight

Parameter containing:
tensor([[ 0.0726, -0.4170, -0.1295, -0.0027,  0.4347]], requires_grad=True)

In [27]:
model.linear.bias

Parameter containing:
tensor([-0.0634], requires_grad=True)

In [29]:
!pip install torchinfo

In [30]:
from torchinfo import summary

summary(model,input_size=(10,5)) #5 inputs weights and one bais

Layer (type:depth-idx)                   Output Shape              Param #
NeuralNetwrok                            [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [49]:
#Define data for the class #ANSWER SHOULD BE binary
x_train = torch.rand(10,5)
y_train = torch.randint(0,2,(10,1))
y_train

tensor([[1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1]])

In [59]:
#Now make with hidden layers
input_shape = 5
hidden_node = 3
ouput_Node = 1
class Neural(nn.Module):

  def __init__(self,input_shape,hidden_node,ouput_Node):
    super().__init__()
    self.sequential = nn.Sequential(  #sequential container
       nn.Linear(input_shape,hidden_node),
       nn.ReLU(),
       nn.Linear(hidden_node,ouput_Node),
       nn.Sigmoid())

  #forward propagation
  def forward(self,features):
    return self.sequential(features)

  def lossFunction(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(y_train * torch.log(y_pred) + (1-y_train) * torch.log(1-y_pred)).mean()
    return loss

In [51]:
#learning rate
lr = 0.01
epochs = 25

In [66]:
model1 = Neural(x_train.shape[1],hidden_node=3,ouput_Node=1)

#define the loop
for epoch in range(epochs):
    y_pred = model1(x_train)
    loss = model1.lossFunction(y_pred,y_train)

    #backward pass
    loss.backward()

    with torch.no_grad():
      model1.sequential[0].weight -= lr * model1.sequential[0].weight.grad
      model1.sequential[0].bias -= lr * model1.sequential[0].bias.grad

    #zero gradient the wiegts
    model1.sequential[0].weight.grad.zero_()
    model1.sequential[0].bias.grad.zero_()

    #print loss in each epochs
    print(f"epoch,{epoch + 1}, loss: {loss.item()}")

epoch,1, loss: 0.687419056892395
epoch,2, loss: 0.6873587965965271
epoch,3, loss: 0.6872986555099487
epoch,4, loss: 0.6872385740280151
epoch,5, loss: 0.6871785521507263
epoch,6, loss: 0.6871185898780823
epoch,7, loss: 0.6870585680007935
epoch,8, loss: 0.6869987845420837
epoch,9, loss: 0.6869390606880188
epoch,10, loss: 0.6868792772293091
epoch,11, loss: 0.6868196725845337
epoch,12, loss: 0.6867600083351135
epoch,13, loss: 0.6867004632949829
epoch,14, loss: 0.6866409182548523
epoch,15, loss: 0.6865814924240112
epoch,16, loss: 0.6865220665931702
epoch,17, loss: 0.6864627599716187
epoch,18, loss: 0.6864035129547119
epoch,19, loss: 0.6863442659378052
epoch,20, loss: 0.6862851977348328
epoch,21, loss: 0.6862260699272156
epoch,22, loss: 0.6861670613288879
epoch,23, loss: 0.6861081719398499
epoch,24, loss: 0.686049222946167
epoch,25, loss: 0.6859903335571289


In [41]:
#Now creat the fake dataset for the nn module
features = torch.rand(10,5)
model1 = Neural(input_shape,hidden_node,ouput_Node)

In [67]:
#Now will use otimizer of inbuilt and loss function
#Now make with hidden layers
input_shape = 5
hidden_node = 3
ouput_Node = 1
loss_function = nn.BCELoss()
class Neural(nn.Module):

  def __init__(self,input_shape,hidden_node,ouput_Node):
    super().__init__()
    self.sequential = nn.Sequential(  #sequential container
       nn.Linear(input_shape,hidden_node),
       nn.ReLU(),
       nn.Linear(hidden_node,ouput_Node),
       nn.Sigmoid())

  #forward propagation
  def forward(self,features):
    return self.sequential(features)

In [69]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [71]:
Model = Neural(x_train.shape[1],hidden_node=3,ouput_Node=1)

#define the loop
for epoch in range(epochs):
    y_pred = Model(x_train)
    loss =loss_function(y_pred,y_train.float())

    #backward propagation
    loss.backward()

    with torch.no_grad():
      for param in Model.parameters():
        param -= lr * param.grad

    #zero gradient the wiegts
    Model.zero_grad()

    #print loss in each epochs
    print(f"epoch,{epoch + 1}, loss: {loss.item()}")

epoch,1, loss: 0.7355154752731323
epoch,2, loss: 0.7355154752731323
epoch,3, loss: 0.7355154752731323
epoch,4, loss: 0.7355154752731323
epoch,5, loss: 0.7355154752731323
epoch,6, loss: 0.7355154752731323
epoch,7, loss: 0.7355154752731323
epoch,8, loss: 0.7355154752731323
epoch,9, loss: 0.7355154752731323
epoch,10, loss: 0.7355154752731323
epoch,11, loss: 0.7355154752731323
epoch,12, loss: 0.7355154752731323
epoch,13, loss: 0.7355154752731323
epoch,14, loss: 0.7355154752731323
epoch,15, loss: 0.7355154752731323
epoch,16, loss: 0.7355154752731323
epoch,17, loss: 0.7355154752731323
epoch,18, loss: 0.7355154752731323
epoch,19, loss: 0.7355154752731323
epoch,20, loss: 0.7355154752731323
epoch,21, loss: 0.7355154752731323
epoch,22, loss: 0.7355154752731323
epoch,23, loss: 0.7355154752731323
epoch,24, loss: 0.7355154752731323
epoch,25, loss: 0.7355154752731323


In [72]:
with torch.no_grad():
  y_pred = Model.forward(x_train)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_train).float().mean()
  print(f"accuracy: {accuracy}") #although acc is not good

accuracy: 0.4000000059604645


generator

In [84]:
#now built in optimizer
#Now make with hidden layers
input_shape = 5
hidden_node = 3
ouput_Node = 1
class Neural(nn.Module):

  def __init__(self,input_shape,hidden_node,ouput_Node):
    super().__init__()
    self.sequential = nn.Sequential(  #sequential container
       nn.Linear(input_shape,hidden_node),
       nn.ReLU(),
       nn.Linear(hidden_node,ouput_Node),
       nn.Sigmoid())

  #forward propagation
  def forward(self,features):
    return self.sequential(features)

Modle = Neural(x_train.shape[1],hidden_node=3,ouput_Node=1)
#define builtin optimizer
#define loss function
optimizer = torch.optim.SGD(Modle.parameters(),lr=0.01)
loss_function = nn.BCELoss()
type(Modle.parameters()) #it is genrator it generat the value on the fly.
epochs = 1000
#define the loop
for epoch in range(epochs):
    y_pred = Modle(x_train)
    loss =loss_function(y_pred,y_train.float())

    optimizer.zero_grad() #for the next epoch last gradient will be zero.
    #backward propagation
    loss.backward()

    optimizer.step() #for paramter update

    #print loss in each epochs
    print(f"epoch,{epoch + 1}, loss: {loss.item()}")
    #print accuracy
    with torch.no_grad():
      y_pred = Modle.forward(x_train)
      y_pred = (y_pred > 0.5).float()
      accuracy = (y_pred == y_train).float().mean()
      print(f"accuracy: {accuracy}")

epoch,1, loss: 0.785914421081543
accuracy: 0.4000000059604645
epoch,2, loss: 0.7847326993942261
accuracy: 0.4000000059604645
epoch,3, loss: 0.783824622631073
accuracy: 0.4000000059604645
epoch,4, loss: 0.7829216718673706
accuracy: 0.4000000059604645
epoch,5, loss: 0.7820240259170532
accuracy: 0.4000000059604645
epoch,6, loss: 0.7811772227287292
accuracy: 0.4000000059604645
epoch,7, loss: 0.7804462313652039
accuracy: 0.4000000059604645
epoch,8, loss: 0.7797192335128784
accuracy: 0.4000000059604645
epoch,9, loss: 0.7789961695671082
accuracy: 0.4000000059604645
epoch,10, loss: 0.7783351540565491
accuracy: 0.4000000059604645
epoch,11, loss: 0.7777438163757324
accuracy: 0.4000000059604645
epoch,12, loss: 0.7771555781364441
accuracy: 0.4000000059604645
epoch,13, loss: 0.7765703797340393
accuracy: 0.4000000059604645
epoch,14, loss: 0.775987982749939
accuracy: 0.4000000059604645
epoch,15, loss: 0.7754086256027222
accuracy: 0.4000000059604645
epoch,16, loss: 0.7748321890830994
accuracy: 0.40000