In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.device_count()

1

In [5]:
torch.cuda.get_device_name(0)

'Tesla T4'

# **Element wise operation**

In [6]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [8]:
torch.clamp(x,min=2,max=4)

tensor([[2, 2, 3],
        [4, 4, 4]])

# **randint operation**

In [16]:
e = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(e)

tensor([[7., 8., 1.],
        [2., 4., 0.],
        [5., 7., 3.]])


# **sum**

In [11]:
torch.sum(e)

tensor(44)

In [12]:
torch.sum(e,dim=0) #0 for columns

tensor([19, 13, 12])

In [14]:
torch.sum(e,dim=1) # 1 for rows

tensor([17,  7, 20])

In [17]:
#Mean
torch.mean(e)

tensor(4.1111)

In [18]:
#Median
torch.median(e)

tensor(4.)

In [19]:
#Mode
torch.mode(e)

torch.return_types.mode(
values=tensor([1., 0., 3.]),
indices=tensor([2, 2, 2]))

In [20]:
#max and min value
print(torch.max(e))
print(torch.min(e))

tensor(8.)
tensor(0.)


In [21]:
#standarization
torch.std(e)

tensor(2.8480)

In [22]:
#argmax
torch.argmax(e)

tensor(1)

In [24]:
#var
torch.var(e)

tensor(8.1111)

In [25]:
#argmin
#argmax
torch.argmin(e)

tensor(5)

In [26]:
#transpose
torch.t(e)

tensor([[7., 2., 5.],
        [8., 4., 7.],
        [1., 0., 3.]])

In [29]:
#determinnant

x = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(x)


torch.det(x)

tensor([[8., 5., 3.],
        [2., 9., 7.],
        [4., 8., 4.]])


tensor(-120.)

In [30]:
#inverse
torch.inverse(x)

tensor([[ 0.1667, -0.0333, -0.0667],
        [-0.1667, -0.1667,  0.4167],
        [ 0.1667,  0.3667, -0.5167]])

In [32]:
#log , exp ,sqrt,softmax
print(torch.softmax(x,dim=0))
print(torch.log(x))
print(torch.sqrt(x))
print(torch.exp(x))

tensor([[0.9796, 0.0132, 0.0171],
        [0.0024, 0.7214, 0.9362],
        [0.0179, 0.2654, 0.0466]])
tensor([[2.0794, 1.6094, 1.0986],
        [0.6931, 2.1972, 1.9459],
        [1.3863, 2.0794, 1.3863]])
tensor([[2.8284, 2.2361, 1.7321],
        [1.4142, 3.0000, 2.6458],
        [2.0000, 2.8284, 2.0000]])
tensor([[2.9810e+03, 1.4841e+02, 2.0086e+01],
        [7.3891e+00, 8.1031e+03, 1.0966e+03],
        [5.4598e+01, 2.9810e+03, 5.4598e+01]])


In [33]:
#relu
torch.relu(x)

tensor([[8., 5., 3.],
        [2., 9., 7.],
        [4., 8., 4.]])

# **Copying a tensor**

In [34]:
x

tensor([[8., 5., 3.],
        [2., 9., 7.],
        [4., 8., 4.]])

In [39]:
b=x    #same memory location
b

tensor([[8., 5., 3.],
        [2., 9., 7.],
        [4., 8., 4.]])

In [36]:
z = x.clone()  #diffrent memory location

In [37]:
id(z)

134265773916000

In [38]:
id(x)

134265774597888

# **tensor operation on gpu**

In [41]:
torch.cuda.is_available()

True

In [42]:
device = torch.device('cuda')

In [43]:
#now tensor on gpu

torch.rand(3,3).to(device) #this tensor will make on the gpu not on the cpu.

tensor([[0.5479, 0.8655, 0.0661],
        [0.5748, 0.4850, 0.7475],
        [0.1058, 0.4881, 0.8535]], device='cuda:0')

In [44]:
x   #cpu tensor which occupied the cpu memory

tensor([[8., 5., 3.],
        [2., 9., 7.],
        [4., 8., 4.]])

In [46]:
z=x.to(device) #existing function will move to gpu

In [47]:
import time

size = 10000

x = torch.rand(size,size)
y = torch.rand(size,size)

start = time.time()

z = torch.matmul(x,y)

end = time.time()

print(end-start)

15.193551063537598


In [48]:
import time

start = time.time()

size = 10000

x = torch.rand(size,size).to(device)
y = torch.rand(size,size).to(device)

z = torch.matmul(x,y).to(device)

end = time.time()

print(end-start)

2.2223315238952637


# ***Reshaping Tensor***

In [52]:
m = torch.rand(3,3)
print(m.shape)

torch.Size([3, 3])


In [60]:
m.flatten() #single row or 1d array

tensor([0.2563, 0.4733, 0.4074, 0.4743, 0.4004, 0.6537, 0.8308, 0.4884, 0.0143])

In [66]:
#unsqueez
x = torch.rand(256,256,3)
print(x.shape)
x.unsqueeze(dim=0).shape

torch.Size([256, 256, 3])


torch.Size([1, 256, 256, 3])

In [67]:
x.squeeze(dim=0).shape

torch.Size([256, 256, 3])

In [68]:
import numpy as np