In [1]:
import torch #import torch

In [2]:
print(torch.__version__)

2.5.1+cu121


In [11]:
if torch.cuda.is_available(): #cuda to check the gpu is haega k nai
    print(f"Gpu haega {torch.cuda.get_device_name(0)}") #0 for number of gpu
else:
    print("Gpu koni hae")


Gpu haega Tesla T4


# **Creating a Tensor**

# **Empty Tensor**

In [14]:
a=torch.empty(2,3) #2 rows and 3 colum empty tensor creat space in memory
print(type(a))

<class 'torch.Tensor'>


# **zero tensor**

In [15]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# **one tensor**

In [16]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

# **random tensor**

In [18]:
torch.rand(2,2) #it make some random intialization

tensor([[0.1645, 0.4956],
        [0.5040, 0.5858]])

# **use of seed**

In [22]:
torch.manual_seed(100) #reproducity
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

# **Custom tensor**

In [24]:
torch.tensor([[2,2],[2,4]]) #it is used for custom tensor

tensor([[2, 2],
        [2, 4]])

In [25]:
#other ways
print("tensor arange",torch.arange(0,12,3))

#linespace
print("Linespace tensor",torch.linspace(0,10,10)) #linearspace

#using eye
print("eye tensor",torch.eye(5)) #identity matrix daignoal will be same

#using full

print("full tensor",torch.full((3,3),5))

tensor arange tensor([0, 3, 6, 9])
Linespace tensor tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
eye tensor tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
full tensor tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# **How to check tensor shapes**

In [29]:
x = torch.tensor([[2,2,2],[2,2,2]])
print(x)
print("shape of tensor",x.shape)

tensor([[2, 2, 2],
        [2, 2, 2]])
shape of tensor torch.Size([2, 3])


In [30]:
torch.empty_like(x) #if we want to make same tensor with diffrent value

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6068937142538677556, 3761977081101694257, 6501284931677008942]])

In [31]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [44]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.6765, 0.7539, 0.2627],
        [0.0428, 0.2080, 0.1180]])

In [32]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# **To check the dataype of tensor**

In [37]:
x.dtype

torch.int64

# **How to specify DataType**

In [39]:
y = torch.tensor([[2,2,2],[2,2,2]],dtype=torch.float32)
y.dtype
print(y)

tensor([[2., 2., 2.],
        [2., 2., 2.]])


# **Change Existing datatype using** ***to***

In [40]:
x.to(torch.float64)

tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)

# **DMAS Operation**

In [47]:
a = torch.rand(2,2)
print(a)

tensor([[0.4183, 0.9014],
        [0.9969, 0.7565]])


In [51]:
#Addition
print("addiditon",x+2)

#subtraction

print("Subtraction",x-2)
#multiplication
print("subtraction",x*2)

#division
print("division",x/2)


#integer division
print("integer divison",(x*100)//3)


addiditon tensor([[4, 4, 4],
        [4, 4, 4]])
Subtraction tensor([[0, 0, 0],
        [0, 0, 0]])
subtraction tensor([[4, 4, 4],
        [4, 4, 4]])
division tensor([[1., 1., 1.],
        [1., 1., 1.]])
integer divison tensor([[66, 66, 66],
        [66, 66, 66]])


# **Element wise operation**

In [10]:
import torch